### ISSUE TITLE
Add a sanity check to ensure restic has been correctly installed

### ISSUE THREAD

**Issue by jrevillard** [arillso/ansible.restic#15]
Hi,

This is not the first time it occurs and I don't know how to reproduce it but it could happen that the restic file is empty:

```
[root@XX ~]# ls -al /usr/bin/restic
lrwxrwxrwx. 1 root root 28 Aug  5 09:04 /usr/bin/restic -> /opt/restic/bin/restic-0.9.6
[root@XX ~]# ls -al  /opt/restic/bin/restic-0.9.6 
-rwxr-xr-x. 1 centos centos 0 Aug  5 08:56 /opt/restic/bin/restic-0.9.6
```

This just occurred to me on 3 servers simultaneously. It would be good to have a checke for this as, in fact, the result is restic which cannot init the repository of course but the error message in my case is that it cannot connect using ssh so I spent hours trying to find the problem...

Best,
Jerome

**Comment by mleutenegger** [comment]
Hi,
thanks for opening an issue. Currently, the Restic binary is extracted using the `bzip2` command here:
https://github.com/arillso/ansible.restic/blob/b3644e79f7bc10d61e3280b6a86821084747d97a/tasks/install.yml#L9-L15

This should be where the error originates, as the task is only executed if the restic binary does not exist (which might have caused the problem). My guess is, that it might be a problem with an uncatched error in the extraction step. If the extraction fails once and we do not catch it, the problem will persist until the faulty file is deleted.

I'll try to reproduce it, but in the meantime, a check would surely be a good start. 

---
PS: I am a bit confused by your Restic telling you that it cannot connect vias ssh, as the initialization step actually executes the command via shell: 😕 
https://github.com/arillso/ansible.restic/blob/b3644e79f7bc10d61e3280b6a86821084747d97a/tasks/configure.yml#L2-L3

**Comment by jrevillard** [comment]
I was confused too.. during hours.... :-) 

Here was the output:

> TASK [ansible.restic : Initialize repository] **********************************
> task path: /home/centos/bigeys-iac/stack/confluent/roles/ansible.restic/tasks/configure.yml:2
> Read vars_file '{{ playbook_dir }}/inventories/{{env}}/secrets.yml'
> Read vars_file '{{ playbook_dir }}/inventories/vars.yml'
> Read vars_file '{{ playbook_dir }}/inventories/{{ env }}/vars.yml'
> Read vars_file '{{ playbook_dir }}/inventories/{{env}}/secrets.yml'
> Read vars_file '{{ playbook_dir }}/inventories/vars.yml'
> Read vars_file '{{ playbook_dir }}/inventories/{{ env }}/vars.yml'
> Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
> Pipelining is enabled.
> <XXXXXXXXXXX> ESTABLISH SSH CONNECTION FOR USER: centos
> <XXXXXXXXXXX> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="centos"' -o ConnectTimeout=10 -o ControlPath=/home/centos/.ansible/cp/b03a3686a3 192.168.131.6 '/bin/sh -c '"'"'RESTIC_REPOSITORY=sftp:backup@BLABLA:/backup/restic/rci/zk3-rci RESTIC_PASSWORD=YYYYYYYYYYYY /usr/bin/python && sleep 0'"'"''
> Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
> Pipelining is enabled.
> <XXXXXXXXXXX> (1, '\n{"exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_command_payload_tho2IG/ansible_command_payload.zip/ansible/module_utils/basic.py\\", line 2564, in run_command\\n    cmd = subprocess.Popen(args, **kwargs)\\n  File \\"/usr/lib64/python2.7/subprocess.py\\", line 711, in __init__\\n    errread, errwrite)\\n  File \\"/usr/lib64/python2.7/subprocess.py\\", line 1327, in _execute_child\\n    raise child_exception\\n", "cmd": "/usr/bin/restic init", "failed": true, "rc": 8, "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "/usr/bin/restic init", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "msg": "[Errno 8] Erreur de format pour exec()"}\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26268\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
> <192.168.131.4> Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 58: Applying options for *
> debug1: auto-mux: Trying existing master
> debug2: fd 3 setting O_NONBLOCK
> debug2: mux_client_hello_exchange: master version 4
> debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
> debug3: mux_client_request_session: entering
> debug3: mux_client_request_alive: entering
> debug3: mux_client_request_alive: done pid = 26268
> debug3: mux_client_request_session: session request sent
> debug1: mux_client_request_session: master session id: 2
> debug3: mux_client_read_packet: read header failed: Broken pipe
> debug2: Received exit status from master 1

Best,
Jerome

**Comment by jrevillard** [comment]
@mleutenegger in fact, to reproduce, simply do not install bzip2 :

```
TASK [ansible.restic : Decompress the binary] *******************************************************************************************************************************************
fatal: [XXXXX]: FAILED! => {"changed": true, "cmd": "bzip2 -dc /opt/restic/restic.bz2 > /opt/restic/bin/restic-0.9.6", "delta": "0:00:00.006630", "end": "2020-08-07 10:14:56.623954", "msg": "non-zero return code", "rc": 127, "start": "2020-08-07 10:14:56.617324", "stderr": "/bin/sh: bzip2 : commande introuvable", "stderr_lines": ["/bin/sh: bzip2 : commande introuvable"], "stdout": "", "stdout_lines": []}
[root@dns ~]# ls -al /opt/restic/bin/restic-0.9.6
-rw-r--r--. 1 root root 0 Aug  7 10:14 /opt/restic/bin/restic-0.9.6
```

Then you fix your playbook but  it's too late !
