### ISSUE TITLE
doc: `restic_install_path` in defaults does not match with the README.

### ISSUE THREAD

**Issue by DO1JLR** [arillso/ansible.restic#41]
By the way, I just noticed with the variable `restic_install_path` that the default values do not match the README.

https://github.com/arillso/ansible.restic/blob/01c777f7d03a4ed448efd14abb2229965b4d8379/defaults/main.yml#L6
https://github.com/arillso/ansible.restic/blob/01c777f7d03a4ed448efd14abb2229965b4d8379/README.md#L70

**Comment by mleutenegger** [comment]
Good Catch! :+1:
