### ISSUE TITLE
Backup success should be logged correctly

### ISSUE THREAD

**Issue by mleutenegger** [arillso/ansible.restic#5]
Each backup (each `src`) will create an output. This output needs to be logged.

Depending on the privileges of the executing user, `/var/logs` may not be accessible. Addition of a dedicated `restic_log_path` could be the solution. Each backup can have its own logfile here.

**Comment by LucaTNT** [comment]
I think my pull request #21 answers this 😊

**Comment by mleutenegger** [comment]
It actually does, will link the PR 🙃
