### ISSUE TITLE
Quotes in Restic password causes the script to fail

### ISSUE THREAD

**Issue by alt4** [arillso/ansible.restic#8]
Greetings!

It seems like having some special chars such single, back or double quotes in the password used for the Restic repo breaks the generated backup script:

```
/root/restic/backup-data.sh: line 7: syntax error near unexpected token `<bits of password>'
/root/restic/backup-data.sh: line 7: `export RESTIC_PASSWORD=<passwordwithquotes>'
```

A potential fix would be to put the whole string between single quotes and escape those in the password, like so:

PasswordWith'Quotes'
`RESTIC_PASSWORD='PasswordWith'\''Quotes'\''`

... But I'm afraid I'm not knowledgeable enough in Ansible to tell if that's feasible easily.

**Comment by mleutenegger** [comment]
Hi,
Thanks for reporting this, I will have a look at the template generation step.
At first glance though it looks like this does not necessarily have a simple solution.

**Comment by mleutenegger** [comment]
I finally managed to get an in-depth look at this issue and it seems to me like this is something very user-specific. Ansible does provide the [`regex_replace` filter](https://docs.ansible.com/ansible/2.3/playbooks_filters.html#other-useful-filters) which could be used to accomplish what this issue proposes.

@alt4  as a workaround, could you try the following:
```yaml
# ...
    password: "PasswordWith\"Quotes\""
# ...
```
This should solve the problem, too.

**Comment by alt4** [comment]
Apologies, last weekend was quite busy. I'll try that soon-ish.

Thank you for your investigation!

**Comment by alt4** [comment]
I've tried what you suggested, it still failed in bash if the password used both single and double quotes. I've also tried to run your `use-regex-escape` branch, but no dice: it escapes characters such as `&` but not `'` for some reason...

Afaik, the most foolproof way to escape characters in bash is to corner the variable with single quotes and just escape the eventual `'`.

Let's say I want to use the password `A'Very'Annoying"Password"`:

```bash
# Not escaped at all
a@b:~$ RESTIC_PASSWORD=A'Very'Annoying"Password"
a@b:~$ echo $RESTIC_PASSWORD
AVeryAnnoyingPassword

# Escaped with single quotes
a@b:~$ RESTIC_PASSWORD='A'\''Very'\''Annoying"Password"'
a@b:~$ echo $RESTIC_PASSWORD
A'Very'Annoying"Password"
```

You don't need to escape the double quotes that way, or any other character for that matter.

Then for Ansible, I suggest using regex_replace rather than regex_escape, since we only have to escape single quotes to make bash happy. 

I used this [on my fork](https://github.com/alt4/ansible.restic/blob/regex-replace/templates/restic_script_Linux.j2) successfully (I can open a pull request, but since you've already got one I'll leave it up to you):
`export RESTIC_PASSWORD='{{ restic_repos[item.repo].password | regex_replace('\'', '\'\\\'\'') }}'`

Note the single quote before and after the Jinja bit, as well as the regex itself replacing `'` to `'\''`.

Bit hacky, but if I'm not mistaken any and all characters used in the password won't cause any issue!

**Comment by mleutenegger** [comment]
Thanks for trying and writing down your solution. The `regex_replace()` would have been my next try. Ill just implement your solution on my patch branch. Would be glad if you could check it out and give feedback, then I would release the change immediately

**Comment by alt4** [comment]
I'm getting `Fatal: unable to open config file: Stat: Access Denied.` using said branch.
Pretty sure it is because `regex_escape()` is still used for `AWS_SECRET_ACCESS_KEY` ([here](https://github.com/arillso/ansible.restic/blob/use-regex-escape/templates/restic_script_Linux.j2#L13)), which escapes dashes in the secret key.

**Comment by mleutenegger** [comment]
My bad, now it should be correctly exchanged

**Comment by alt4** [comment]
All good now, works perfectly.

One last nitpick though: you are still using `"` around `AWS_SECRET_ACCESS_KEY`. I am not sure it would work as expected if there was a single quote in the key.

**Comment by mleutenegger** [comment]
That sounds great! I‘ll correct the last nitpick and merge!

Thanks for the help
